
export type FinancialReportItem = {
    id: string;
    name: string;
    amount: number;
    level: number; // indentation level
    type: "HEADER" | "ITEM" | "TOTAL";
    children?: FinancialReportItem[];
};

export const profitLossData: FinancialReportItem[] = [
    {
        id: "INC",
        name: "PENDAPATAN",
        amount: 0,
        level: 0,
        type: "HEADER",
    },
    {
        id: "INC-001",
        name: "Penjualan Bersih",
        amount: 1250000000,
        level: 1,
        type: "ITEM",
    },
    {
        id: "INC-002",
        name: "Pendapatan Jasa",
        amount: 150000000,
        level: 1,
        type: "ITEM",
    },
    {
        id: "INC-TOT",
        name: "Total Pendapatan",
        amount: 1400000000,
        level: 0,
        type: "TOTAL",
    },
    {
        id: "COGS",
        name: "HARGA POKOK PENJUALAN",
        amount: 0,
        level: 0,
        type: "HEADER",
    },
    {
        id: "COGS-001",
        name: "HPP Barang Dagang",
        amount: -850000000,
        level: 1,
        type: "ITEM",
    },
    {
        id: "GP",
        name: "LABA KOTOR",
        amount: 550000000,
        level: 0,
        type: "TOTAL",
    },
    {
        id: "EXP",
        name: "BEBAN OPERASIONAL",
        amount: 0,
        level: 0,
        type: "HEADER",
    },
    {
        id: "EXP-001",
        name: "Beban Gaji & Tunjangan",
        amount: -125000000,
        level: 1,
        type: "ITEM",
    },
    {
        id: "EXP-002",
        name: "Beban Sewa",
        amount: -45000000,
        level: 1,
        type: "ITEM",
    },
    {
        id: "EXP-003",
        name: "Beban Listrik & Air",
        amount: -12500000,
        level: 1,
        type: "ITEM",
    },
    {
        id: "EXP-004",
        name: "Beban Pemasaran",
        amount: -35000000,
        level: 1,
        type: "ITEM",
    },
    {
        id: "EXP-TOT",
        name: "Total Beban Operasional",
        amount: -217500000,
        level: 0,
        type: "TOTAL",
    },
    {
        id: "OP",
        name: "LABA OPERASIONAL",
        amount: 332500000,
        level: 0,
        type: "TOTAL",
    },
    {
        id: "TAX",
        name: "Pajak Penghasilan (Estimasi)",
        amount: -73150000,
        level: 1,
        type: "ITEM",
    },
    {
        id: "NP",
        name: "LABA BERSIH",
        amount: 259350000,
        level: 0,
        type: "TOTAL",
    },
];

export const balanceSheetData: FinancialReportItem[] = [
    {
        id: "AST",
        name: "ASET",
        amount: 0,
        level: 0,
        type: "HEADER",
    },
    {
        id: "AST-CUR",
        name: "Aset Lancar",
        amount: 0,
        level: 1,
        type: "HEADER",
    },
    {
        id: "AST-001",
        name: "Kas & Bank",
        amount: 450000000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "AST-002",
        name: "Piutang Usaha",
        amount: 125000000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "AST-003",
        name: "Persediaan",
        amount: 350000000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "AST-CUR-TOT",
        name: "Total Aset Lancar",
        amount: 925000000,
        level: 1,
        type: "TOTAL",
    },
    {
        id: "AST-FIX",
        name: "Aset Tetap",
        amount: 0,
        level: 1,
        type: "HEADER",
    },
    {
        id: "AST-004",
        name: "Peralatan Kantor",
        amount: 85000000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "AST-005",
        name: "Kendaraan",
        amount: 250000000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "AST-006",
        name: "Akumulasi Penyusutan",
        amount: -45000000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "AST-FIX-TOT",
        name: "Total Aset Tetap",
        amount: 290000000,
        level: 1,
        type: "TOTAL",
    },
    {
        id: "AST-TOT",
        name: "TOTAL ASET",
        amount: 1215000000,
        level: 0,
        type: "TOTAL",
    },
    {
        id: "LIA",
        name: "LIABILITAS & EKUITAS",
        amount: 0,
        level: 0,
        type: "HEADER",
    },
    {
        id: "LIA-CUR",
        name: "Liabilitas Lancar",
        amount: 0,
        level: 1,
        type: "HEADER",
    },
    {
        id: "LIA-001",
        name: "Hutang Usaha",
        amount: 185000000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "LIA-002",
        name: "Hutang Pajak",
        amount: 25000000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "LIA-CUR-TOT",
        name: "Total Liabilitas",
        amount: 210000000,
        level: 1,
        type: "TOTAL",
    },
    {
        id: "EQU",
        name: "Ekuitas",
        amount: 0,
        level: 1,
        type: "HEADER",
    },
    {
        id: "EQU-001",
        name: "Modal Disetor",
        amount: 745650000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "EQU-002",
        name: "Laba Ditahan",
        amount: 259350000,
        level: 2,
        type: "ITEM",
    },
    {
        id: "EQU-TOT",
        name: "Total Ekuitas",
        amount: 1005000000,
        level: 1,
        type: "TOTAL",
    },
    {
        id: "LIA-EQU-TOT",
        name: "TOTAL LIABILITAS & EKUITAS",
        amount: 1215000000,
        level: 0,
        type: "TOTAL",
    },
];

export const monthlyRevenueData = [
    { name: "Jan", revenue: 180000000, expense: 120000000 },
    { name: "Feb", revenue: 220000000, expense: 135000000 },
    { name: "Mar", revenue: 195000000, expense: 125000000 },
    { name: "Apr", revenue: 250000000, expense: 145000000 },
    { name: "Mei", revenue: 280000000, expense: 160000000 },
    { name: "Jun", revenue: 275000000, expense: 140000000 },
];
