-- CreateEnum
CREATE TYPE "AccountSubType" AS ENUM ('ASSET_RECEIVABLE', 'ASSET_CASH', 'ASSET_CURRENT', 'ASSET_NON_CURRENT', 'ASSET_PREPAYMENTS', 'ASSET_FIXED', 'LIABILITY_PAYABLE', 'LIABILITY_CURRENT', 'LIABILITY_NON_CURRENT', 'EQUITY', 'EQUITY_UNAFFECTED', 'INCOME', 'INCOME_OTHER', 'EXPENSE', 'EXPENSE_DEPRECIATION', 'EXPENSE_DIRECT_COST', 'GENERAL');

-- AlterTable
ALTER TABLE "gl_accounts" ADD COLUMN "subType" "AccountSubType" NOT NULL DEFAULT 'GENERAL';
